### ISSUE TITLE
DNN 9.1.1 - Left Persona Bar pushes top menu bar over

### ISSUE THREAD

**Issue by JaySMa** [dnnconsulting/DnnC.Contra#3]
When logged in, the persona bar pushes the top icon bar over.

When logged in, you only see the Profile Avatar, Check Messages, and Check Notifications without any scroll bar at the bottom.

**Comment by dnnconsulting** [comment]
Hi Jaysma,
We have seen this and its not a bug on the theme, it effects every theme and the Personabar not only pushes the top bar over to the right, its the whole site. You only see this (depending on your screen size) when the site is full width.

When I have time I'll find a solution for this.
Regards,
Geoff.
