### ISSUE TITLE
Missing container files

### ISSUE THREAD

**Issue by roman-yagodin** [dnnconsulting/DnnC.Contra#4]
Container files referenced in the `DnnContra.dnn` aren't available in the source tree.

**Comment by dnnconsulting** [comment]
Can you explain what you mean with the comment above please, don't understand what you mean

**Comment by roman-yagodin** [comment]
The container files like `Title-Arrow-H1.ascx` only available in the install package, but there is no such files in the code repository.

**Comment by dnnconsulting** [comment]
ok, gotcha, you would like them on Github as well?

**Comment by dnnconsulting** [comment]
done.

**Comment by roman-yagodin** [comment]
Thanks!

**Comment by roman-yagodin** [comment]
Didn't saw `Card-block-h3.ascx` before - and it isn't referenced in the manifest.
