### ISSUE TITLE
Missing sources for CSS

### ISSUE THREAD

**Issue by roman-yagodin** [dnnconsulting/DnnC.Contra#5]
Color variations provided in minified state, so while it is possible to alter rules in `_base.css`, it is difficult to propagate changes into color variation files.

**Comment by dnnconsulting** [comment]
This is done so that the files are small, if you want to change 1 of the themed css files you can you a beautifier such as this one:

https://www.cleancss.com/css-beautify/

**Comment by roman-yagodin** [comment]
It's viable option, thanks.

But I still doubt that there is a place for minified CSS in the source code, so having CSS (or maybe SCSS) source plus a build script (webpack config or something like that) would be much more convenient.
